FORMAT: 1A
HOST: http://www.google.com

# LazyTimes
LazyTimes API is a simple time report tool.

# Group Report
Time report related resources of the **LazyTimes API**

## Total time reports [/reports]
### Get current total reports [GET]
+ Response 200 (application/json)

        { "project": [
            { "title": "jetpak", "total": { "amount": 32, "unit": "hours" }, "period": { "start": 2014-03-01, "end": 2014-05-14 }, "status": "active" },
            { "title": "actic", "total": { "amount": 12, "unit": "hours" }, "period": { "start": 2014-04-15, "end": 2014-05-14 }, "status": "active" },
            { "title": "ab", "total": { "amount": 1234, "unit": "hours" }, "period": { "start": 2013-12-15, "end": 2014-04-10 }, "status": "inactive" }
            ]
        }

## Time report for period [/reports/{periodLength}]        
### Get current reports for period [GET]
+ Response 200 (application/json)

        { 
            "periodName": "week 20"
            "project": [
            { 
                "title": "jetpak", 
                "total": { 
                    "amount": 32, 
                    "unit": "hours" 
                }, 
                "period": { 
                    "start": 2014-04-12, 
                    "end": 2014-05-17 
                }, 
                "status": "active" 
            },
            { 
                "title": "actic", 
                "total": { 
                    "amount": 12, 
                    "unit": "hours"
                }, 
                "period": { 
                    "start": 2014-04-12, 
                    "end": 2014-05-17 
                }, 
                "status": "active"
            } ]
        }
        
## Total time reports [/reports/{project}]
### Get current total reports [GET]
+ Response 200 (application/json)

        { "project": [
            { "title": "jetpak", "total": { "amount": 32, "unit": "hours" }, "period": { "start": 2014-03-01, "end": 2014-05-14 }, "status": "active" },
            { "title": "actic", "total": { "amount": 12, "unit": "hours" }, "period": { "start": 2014-04-15, "end": 2014-05-14 }, "status": "active" },
            { "title": "ab", "total": { "amount": 1234, "unit": "hours" }, "period": { "start": 2013-12-15, "end": 2014-04-10 }, "status": "inactive" }
            ]
        }
        
### Get current total reports [POST]
+ Request (application/json)

        {
        }

+ Response 200 (application/json)
          
        { 
            "title": "jetpak", 
            "total": { 
                "amount": 32, 
                "unit": "hours" 
            }, 
            "period": { 
                "start": 2014-03-01, 
                "end": 2014-05-14 
            }, 
            "status": "active" 
        }

## Time report for period of project [/reports/{project}/{periodLength}]        
### Get current reports for period [GET]
+ Response 200 (application/json)

        { "project": [
            { "title": "jetpak", "total": { "amount": 32, "unit": "hours" }, "period": { "start": 2014-04-12, "end": 2014-05-17 }, "status": "active" },
            { "title": "actic", "total": { "amount": 12, "unit": "hours" }, "period": { "start": 2014-04-12, "end": 2014-05-17 }, "status": "active" }
            ],
           "periodName": "week 20"
        }


## Reporting [/report/{project}/{time_unit}]
### Report [POST]
+ Response 201 (application/json)

        { "id": 1,
        }

## Reporting [/report/{project}/{date}/{time_unit}]
### Report [GET]
+ Response 201 (application/json)

        { "id": 1,
        }

## Notes Collection [/notes]
### Report [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
